"use client";

import { useState, useEffect } from "react";
import { BiTimeFive } from "react-icons/bi";

export default function OTPVerification() {
    const [timeLeft, setTimeLeft] = useState(30);

    useEffect(() => {
        if (!timeLeft) return;
        const intervalId = setInterval(() => {
            setTimeLeft(timeLeft - 1);
        }, 1000);
        return () => clearInterval(intervalId);
    }, [timeLeft]);

    return (
        <div className="flex min-h-screen items-center justify-center bg-white dark:bg-neutral-950 px-4">
            <div className="w-full max-w-md space-y-8">
                <div className="text-center">
                    <span className="inline-flex h-12 w-12 items-center justify-center rounded-xl bg-orange-100 dark:bg-orange-500/10 text-orange-600 dark:text-orange-400">
                        <BiTimeFive className="h-6 w-6" />
                    </span>
                    <h2 className="mt-6 text-3xl font-bold tracking-tight text-neutral-900 dark:text-white">Authentication Required</h2>
                    <p className="mt-2 text-sm text-neutral-600 dark:text-neutral-400">
                        Please enter the One-Time Password generated by your authenticator app.
                    </p>
                </div>

                <div className="mt-8">
                    <form className="mt-6">
                        <div className="flex flex-col space-y-4">
                            <div className="relative">
                                <input
                                    type="text"
                                    id="otp"
                                    name="otp"
                                    placeholder="Enter 6-digit code"
                                    className="block w-full rounded-md border-0 py-3 text-center text-2xl tracking-[0.5em] font-mono text-neutral-900 shadow-sm ring-1 ring-inset ring-neutral-300 placeholder:text-neutral-300 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6 dark:bg-neutral-900 dark:ring-neutral-700 dark:text-white dark:placeholder:text-neutral-600"
                                    maxLength={6}
                                />
                            </div>

                            <button
                                type="submit"
                                className="flex w-full justify-center rounded-md bg-indigo-600 px-3 py-2 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:ring-2 focus-visible:ring-offset-2 focus-visible:ring-indigo-600"
                            >
                                Authenticate
                            </button>
                        </div>
                    </form>

                    <div className="mt-6 text-center text-sm">
                        {timeLeft > 0 ? (
                            <p className="text-neutral-500">
                                Code expires in <span className="font-semibold text-neutral-900 dark:text-white">{timeLeft}s</span>
                            </p>
                        ) : (
                            <button type="button" className="font-semibold text-indigo-600 hover:text-indigo-500 dark:text-indigo-400" onClick={() => setTimeLeft(30)}>
                                Send new code
                            </button>
                        )}
                    </div>
                </div>
            </div>
        </div>
    )
}
