"use client";

import { BiShield, BiArrowBack } from "react-icons/bi";

export default function TwoFactorSplit() {
    return (
        <div className="flex min-h-screen bg-white dark:bg-neutral-950">
            {/* Form Side */}
            <div className="w-full lg:w-1/2 flex flex-col justify-center py-12 px-4 sm:px-6 lg:px-20 xl:px-24">
                <div className="mx-auto w-full max-w-sm">
                    <button className="flex items-center text-sm text-neutral-500 hover:text-neutral-900 dark:hover:text-neutral-300 mb-8 transition-colors">
                        <BiArrowBack className="mr-2" /> Back to Login
                    </button>

                    <div className="mb-8">
                        <div className="w-12 h-12 bg-blue-100 dark:bg-blue-900/30 text-blue-600 dark:text-blue-400 rounded-xl flex items-center justify-center mb-6">
                            <BiShield className="w-6 h-6" />
                        </div>
                        <h2 className="text-2xl font-bold tracking-tight text-neutral-900 dark:text-white">
                            Verify your identity
                        </h2>
                        <p className="mt-2 text-sm text-neutral-500 dark:text-neutral-400">
                            Enter the 6-digit code generated by your authenticator app.
                        </p>
                    </div>

                    <form className="space-y-6">
                        <div>
                            <label htmlFor="code" className="block text-sm font-medium text-neutral-700 dark:text-neutral-300">
                                Authenticator Code
                            </label>
                            <div className="mt-2">
                                <input
                                    type="text"
                                    className="block w-full rounded-md border-0 py-2.5 text-neutral-900 shadow-sm ring-1 ring-inset ring-neutral-300 placeholder:text-neutral-400 focus:ring-2 focus:ring-inset focus:ring-blue-600 sm:text-sm sm:leading-6 dark:bg-neutral-900 dark:ring-neutral-700 dark:text-white"
                                    placeholder="000 000"
                                    style={{ letterSpacing: '0.2em' }}
                                />
                            </div>
                        </div>

                        <button
                            type="submit"
                            className="flex w-full justify-center rounded-md bg-blue-600 px-3 py-2.5 text-sm font-semibold leading-6 text-white shadow-sm hover:bg-blue-500 focus-visible:ring-2 focus-visible:ring-2 focus-visible:ring-offset-2 focus-visible:ring-blue-600"
                        >
                            Verify Identity
                        </button>
                    </form>

                    <p className="mt-6 text-center text-sm text-neutral-500 dark:text-neutral-400">
                        Lost access to your device?{' '}
                        <a href="#" className="font-medium text-blue-600 hover:text-blue-500 dark:text-blue-400">
                            Use backup code
                        </a>
                    </p>
                </div>
            </div>

            {/* Image Side */}
            <div className="hidden lg:block relative w-1/2">
                <img
                    className="absolute inset-0 h-full w-full object-cover"
                    src="https://images.unsplash.com/photo-1563986768609-322da13575f3?q=80&w=1470&auto=format&fit=crop"
                    alt="Security"
                />
                <div className="absolute inset-0 bg-blue-900/20 mix-blend-multiply" />
            </div>
        </div>
    )
}
